cart_controllers:
    resource: ../../src/Cart/Infrastructure/Api/
    type: annotation
product_controllers:
    resource: ../../src/Product/Infrastructure/Api/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
